# SOURCE: https://github.com/pmav99/python-logging-example/blob/master/log_config.yml
# https://gitter.im/tiangolo/fastapi?at=5e42d5de45000661fcb433a1
---
version: 1
disable_existing_loggers: false
formatters:
  brief:
    format: '%(levelname)-8s; %(name)-35s; %(message)s'
    datefmt: "%I:%M:%S"
  standard:
    format: '%(asctime)s; %(levelname)-8s; %(name)-35s; %(funcName)-20s;%(lineno)4d: %(message)s'
    datefmt: "%I:%M:%S"
  multi_process:
    class: 'logging.Formatter'
    format: '%(asctime)s; %(levelname)-8s; [%(thread;)s]; %(name)-35s; %(funcName)-20s;%(lineno)-4d: %(message)s'
  multi_thread:
    class: 'logging.Formatter'
    format: '%(asctime)s; %(levelname)-8s; [%(process)d]; %(name)-35s; %(funcName)-20s;%(lineno)-4d: %(message)s'
  verbose:
    class: 'logging.Formatter'
    format: '%(asctime)s; %(levelname)-8s; [%(process)d - %(thread)s]; %(name)-35s; %(funcName)-20s;%(lineno)4d: %(message)s'
  multi_line:
    class: 'logging.Formatter'
    format: 'Level: %(levelname)s\nTime: %(asctime)s\nProcess: %(process)d\nThread: %(thread)s\nLogger: %(name)s\nPath: %(module)s:%(lineno)d\nFunction :%(funcName)s\nMessage: %(message)s\n'
  json:
    class: 'pythonjsonlogger.jsonlogger.JsonFormatter'
    format: '%(asctime)s %(levelname)s %(name)s %(module)s %(funcName)s %(filename)s %(lineno)s %(request_id)s %(message)s'
handlers:
  console:
    level: 'DEBUG'
    class: 'logging.StreamHandler'
    formatter: 'verbose'
    stream : 'ext://sys.stdout'
  file_handler:
    level: 'INFO'
    class: 'logging.handlers.WatchedFileHandler'
    formatter: 'verbose'
    filename: '/tmp/ultron8.log'
    mode: 'a'
    encoding: 'utf-8'
loggers:
  ultron8:
    level: 'DEBUG'
    propagate: false
    handlers:
      - 'console'
  requests:
    level: 'WARNING'
    handlers:
      - 'console'
  urllib3:
    level: 'WARNING'
    handlers:
      - 'console'
  sqlalchemy:
    level: 'WARNING'
    handlers:
      - 'console'
root:
  level: 'DEBUG'
  handlers:
    - 'console'
    # - 'file_handler'
