# SOURCE: https://pre-commit.com/hooks.html
# SOURCE: github.com/Yelp/Tron

exclude: '^(contrib|docs/conf.py|docs/gfx)'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    - id: check-ast
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=no']
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    # -   id: check-json
    -   id: check-yaml
    # -   id: flake8
    #    exclude: testifycompat/
# -   repo: https://github.com/asottile/reorder_python_imports.git
#     rev: v1.3.2
#     hooks:
#     -   id: reorder-python-imports
#         language_version: python3.6
-   repo: local
    hooks:
    -   id: patch-enforce-autospec
        name: mock.patch enforce autospec
        description: This hook ensures all mock.patch invocations specify an autospec
        entry: contrib/mock_patch_checker.py
        language: script
        files: ^tests/.*\.py$
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: v4.3.4
#   hooks:
#   - id: isort
#     args: ["--recursive","--check-only","--diff","--verbose","./ultron8","./tests"]
