# -*- coding: utf-8 -*-

# language: python

# python:
#   - "3.6"
#   - "3.7"

# install:
#   - pip install --editable . # Install it self
#   - pip install -r requirements-test.txt # Install test dependencies
#   - pip install codecov # Install coveralls

# script:
#   - pytest tests --cov=ultron8 # Run unittest

# notifications:
#   email: false # Mute email notification

# after_success:
#   - codecov # travis-ci will transfer data to codecov after success
env:
  global:
    - PYTHON="python3"
    - TOXENV=py36
    - PYTHON="python3"
    - DOCKER_COMPOSE_VERSION=1.24.0
    - DOCKER_VERSION=18.09
    - IS_CI_ENVIRONMENT="true"

matrix:
  fast_finish: true
  include:
  - name: "Python 3.6 w/ Docker Compose 1.24.0 and Docker 18.09"
    python: '3.6'
    env:
      # TOX_ENV: py36 # from airflowci
      TOXENV: py36
      PYTHON: "python3"
      # DOCKER_COMPOSE_VERSION: 1.17.1
      DOCKER_COMPOSE_VERSION: 1.24.0
      # TEST_TARGET: default
      # DOCKER_DATA: "$HOME/docker_data"
      # DOCKER_VERSION: 18.09.1~3-0~ubuntu-xenial
      DOCKER_VERSION: 18.09
      IS_CI_ENVIRONMENT: "true"
    sudo: required
    dist: xenial
    language: python
    group: edge
  allow_failures:
  - python: '3.6'
    env:
      TOXENV: typing

services:
  - docker

stages:
  - pre-test
  - test

# SOURCE: https://github.com/apache/airflow/blob/669b026c0bed36572ff0c5ab2eaf3f6d2c845577/.travis.yml
jobs:
  include:
    # - name: Flake8
    #   python: '3.6'
    #   sudo: required
    #   dist: xenial
    #   language: python
    #   group: edge
    #   env:
    #     - PYTHON="python3"
    #   stage: pre-test
    #   install: pip install $(grep "^flake8==" requirements-test.txt | awk '{print $1}')
    #   script: flake8

    - name: mypy
      python: '3.6'
      sudo: required
      dist: xenial
      language: python
      group: edge
      env:
        - PYTHON="python3"
      stage: pre-test
      install: pip install $(grep "^mypy==" requirements-test.txt | awk '{print $1}')
      script: mypy ultron8 tests

    # - name: Lint Dockerfile
    #   python: '3.6'
    #   sudo: required
    #   dist: xenial
    #   language: python
    #   group: edge
    #   env:
    #     - PYTHON="python3"
    #   stage: pre-test
    #   install: skip
    #   script: .ci/ci_lint_dockerfile.sh

    # - name: Check docs
    #   python: '3.6'
    #   sudo: required
    #   dist: xenial
    #   language: python
    #   group: edge
    #   env:
    #     - PYTHON="python3"
    #   stage: pre-test
    #   install: pip install -e .[docs]
    #   script: make build_doc

    - name: Pylint
      python: '3.6'
      sudo: required
      dist: xenial
      language: python
      group: edge
      env:
        - PYTHON="python3"
      stage: pre-test
      install: pip install $(grep "^pylint==" requirements-dev.txt | awk '{print $1}')
      script: pylint --rcfile ./lint-configs-python/python/pylintrc ultron8/consts.py
      cache: false

    - name: Black
      python: '3.6'
      sudo: required
      dist: xenial
      language: python
      group: edge
      env:
        - PYTHON="python3"
      stage: pre-test
      install: pip install $(grep "^black==" requirements-dev.txt | awk '{print $1}')
      script: black --check --exclude=ultron8_venv* --verbose ultron8
      cache: false

    - name: Pytest
      python: '3.6'
      sudo: required
      dist: xenial
      language: python
      group: edge
      env:
        - PYTHON="python3"
      stage: test
      install:
        - pip install --upgrade pip
        - travis_retry pip install coveralls
        - travis_retry pip install coverage
        - travis_retry docker-compose -f docker-compose.ci.yml pull
        - travis_retry make dc-ci-build
      script:
        - travis_retry make dc-ci-run
      # source: https://github.com/inspirehep/inspire-next/blob/9700274c36074a3e43168bf48b8ba3e3bfa7bcdf/.travis.yml
      after_script:
        # Killing via SIGTERM in order to trigger atexit and dump coverage information in WSGI
        - "docker-compose -f docker-compose.ci.yml kill -s SIGTERM"
        - "docker-compose -f docker-compose.ci.yml rm -f"
        # - docker kill ultron8_ci
      after_success:
      - _USER=$(ls -lta | awk '{print $3}')
      - _GROUP=$(ls -lta | awk '{print $4}')
      - docker ps -a
      - 'ls -lta'
      - 'sudo chown $_USER:$_GROUP -Rv *'
      - sudo mv .coverage .coverage.tests
      ################################################################################################
      # NOTE: https://coverage.readthedocs.io/en/coverage-4.5.1/changes.html?highlight=clean
      # Version 4.2b1 — 2016-07-04
      # BACKWARD INCOMPATIBILITY: the coverage combine command now ignores an existing .coverage data file. It used to include that file in its combining. This caused confusing results, and extra tox “clean” steps. If you want the old behavior, use the new coverage combine --append option.
      # ################################################################################################
      # NOTE: Version 4.5 — 2018-02-03
      # The coverage combine command used to always overwrite the data file, even when no data had been read from apparently combinable files. Now, an error is raised if we thought there were files to combine, but in fact none of them could be used. Fixes issue 629.
      - coverage combine
      # Coverage report contains Docker paths. We replace them, so that we can run Coveralls.
      - sed -i 's@\"/home/developer/app/@'"\"$(pwd)/"'@g' .coverage
      - coveralls



before_install:
  - sudo apt-get update
  - travis_retry pip install coveralls

  - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-cache search docker
  - apt-cache madison docker-ce
  - sudo apt-get --allow-downgrades -y -o Dpkg::Options::="--force-confnew" install docker-ce=$(apt-cache madison docker-ce | grep $DOCKER_VERSION | head -1 | awk '{print $3}')

  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install:
  - pip install --upgrade pip
  - travis_retry pip install coveralls
  - travis_retry pip install coverage
  - travis_retry docker-compose -f docker-compose.ci.yml pull
  - travis_retry make dc-ci-build

script:
  - travis_retry make dc-ci-run

# source: https://github.com/inspirehep/inspire-next/blob/9700274c36074a3e43168bf48b8ba3e3bfa7bcdf/.travis.yml
after_script:
  # Killing via SIGTERM in order to trigger atexit and dump coverage information in WSGI
  - "docker-compose -f docker-compose.ci.yml kill -s SIGTERM"
  - "docker-compose -f docker-compose.ci.yml rm -f"
  # - docker kill ultron8_ci

after_success:
  - _USER=$(ls -lta | awk '{print $3}')
  - _GROUP=$(ls -lta | awk '{print $4}')
  - docker ps -a
  - 'ls -lta'
  - 'sudo chown $_USER:$_GROUP -Rv *'
  - sudo mv .coverage .coverage.tests
  ################################################################################################
  # NOTE: https://coverage.readthedocs.io/en/coverage-4.5.1/changes.html?highlight=clean
  # Version 4.2b1 — 2016-07-04
  # BACKWARD INCOMPATIBILITY: the coverage combine command now ignores an existing .coverage data file. It used to include that file in its combining. This caused confusing results, and extra tox “clean” steps. If you want the old behavior, use the new coverage combine --append option.
  # ################################################################################################
  # NOTE: Version 4.5 — 2018-02-03
  # The coverage combine command used to always overwrite the data file, even when no data had been read from apparently combinable files. Now, an error is raised if we thought there were files to combine, but in fact none of them could be used. Fixes issue 629.
  - coverage combine
  # Coverage report contains Docker paths. We replace them, so that we can run Coveralls.
  - sed -i 's@\"/home/developer/app/@'"\"$(pwd)/"'@g' .coverage
  - coveralls

notifications:
  email:
    recipients:
      - bossjones@theblacktonystark.com
    on_success: change # default: change
    on_failure: change # default: always


before_cache:
  - _USER=$(ls -lta | awk '{print $3}')
  - _GROUP=$(ls -lta | awk '{print $4}')
  - 'sudo chown $_USER:$_GROUP -Rv $HOME/.cache/pip $HOME/.wheelhouse/'

cache:
  directories:
    - $HOME/.wheelhouse/
    - $HOME/.cache/pip
    - $HOME/.travis_cache/
