FROM bossjones/ultron8-hacking:0.2.0

# container user
ARG CONTAINER_GID=501
ARG CONTAINER_UID=501
ARG CONTAINER_USER=developer
ARG PYENV_VERSION=3.7.4

# host ip address
ARG HOST_IP

# set container user as environment variable
ENV CONTAINER_USER=${CONTAINER_USER}
ENV PYENV_VERSION=${PYENV_VERSION}

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

RUN apk add bash-completion

USER ${CONTAINER_USER}
WORKDIR /home/${CONTAINER_USER}
ENV LANG C.UTF-8

# COPY --chown=developer:developer . /home/developer/app

COPY --chown=developer:developer requirements.txt requirements.txt
COPY --chown=developer:developer requirements-dev.txt requirements-dev.txt
COPY --chown=developer:developer requirements-doc.txt requirements-doc.txt
COPY --chown=developer:developer requirements-test.txt requirements-test.txt
COPY --chown=developer:developer Pipfile Pipfile
COPY --chown=developer:developer Pipfile.lock Pipfile.lock

# Copy over everything required to run tox
COPY --chown=developer:developer setup.cfg setup.py tox.ini ./
COPY --chown=developer:developer ultron8/__init__.py ultron8/__init__.py

COPY --chown=developer:developer dev-bashrc.sh .
RUN "./dev-bashrc.sh"

RUN pyenv shell 3.7.4; pipenv --python 3.7.4 && pipenv install --dev --deploy

ENV PATH="/home/${CONTAINER_USER}/.local/bin:${PATH}"
