version: '3'
services:
  ultron8_ci:
    container_name: ultron8_ci
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # UID: ${UID}
        # GID: ${GID}
        CONTAINER_GID: ${CONTAINER_GID:-1000}
        CONTAINER_UID: ${CONTAINER_UID:-1000}
    # command: sh
    tty: true
    stdin_open: true
    entrypoint:
      - bash
    command: /home/developer/app/.ci/pytest_runner.sh
    user: ${CONTAINER_UID:-1000}:${CONTAINER_GID:-1000}
    volumes:
      - .:/home/developer/app
    # ports:
    #   - ${PORT}:3000
