# https://gist.github.com/gnarf/b103e77f37236ca72d8e
# SOURCE: \cat roles/*/vagrant-config.yml | pbcopy
:vms:
  ultron8:
    :hostname: "ultron8"
    :name: "ultron8"
    :type: "master"
    :box: "ubuntu/bionic64"
    :eth1: "192.168.2.8"
    :ip: "192.168.2.8"
    :mem: 2048
    :ram: 2048
    :cpu: 2
    :id: 10
    :disk: "10gb"
    # settings[:disk]
