# st2common

__all__ = [
    "SUCCESS_EXIT_CODE",
    "FAILURE_EXIT_CODE",
    "SIGKILL_EXIT_CODE",
    "SIGTERM_EXIT_CODE",
]

SUCCESS_EXIT_CODE = 0
FAILURE_EXIT_CODE = 1
SIGKILL_EXIT_CODE = 9
SIGTERM_EXIT_CODE = 15
