---
clusters_path: clusters/
cache_path: cache/
workspace_path: workspace/
templates_path: templates/

# beard_paths:
#   - beards/
#   - beard_cache/

# beards:
#   - debugbeard

# stache_paths:
#   - moustaches

# staches:
#   - postcats

# db_url: sqlite:///skybeard-2.db
# db_bin_path: ./db_binary_entries

# admins:
#   [
#   [My name, 99999999],
#   ]

# host: 0.0.0.0
# port: 8000

flags:
    debug: 0
    verbose: 0
    keep: 0
    stderr: 0
    repeat: 1

clusters:
    instances:
        local:
            url: 'http://localhost:11267'
            token: ''
