#!/usr/bin/env bash

_PYTHON_VERSION=$(python --version)

if [ "$_PYTHON_VERSION" != "Python 3.6.8" ]; then
    echo "ERROR, Not using the correct version of python, please run 'pyenv shell 3.6.8'"
    return 2
else
    echo "GOOD, Using Python 3.6.8"
    return 0
fi
