#!/bin/bash

set -e

_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "IS_CI_ENVIRONMENT" == "true" ]; then
    export CONTAINER_UID=$(ls -lta | awk '{print $3}')
    export CONTAINER_GID=$(ls -lta | awk '{print $4}')
else
    export CONTAINER_UID=$(id -u)
    export CONTAINER_GID=$(id -g)
fi

PR_SHA=$(git rev-parse HEAD)
REPO_NAME=bossjones/ultron8-ci
IMAGE_TAG=${REPO_NAME}:${PR_SHA}

TAG="${IMAGE_TAG}"

echo " [run] Remove possibly previous broken stacks left hanging after an error"
docker-compose -f docker-compose.ci.yml down -v --remove-orphans

echo " [run] docker-compose up daemonized"
docker-compose -f docker-compose.ci.yml -f docker-compose.web.yml up -d

# echo " [run] docker-compose logs"
# docker-compose -f docker-compose.ci.yml -f docker-compose.web.yml logs --no-color ultron8_ci
