#!/usr/bin/env bash

pushd "$(dirname "$0")/.."

_TEMPDIR=`mktemp -t -d ultron8-pipenv.XXXXXXXXXX` || exit 1
_FILE="$_TEMPDIR/ultron8-pipenv.txt"

cat <<EOF > ${_FILE}
[[source]]
url = "https://pypi.org/simple/"
verify_ssl = true
name = "pypi"

[scripts]
test="py.test --cov-config .coveragerc --verbose --cov-report term --cov-report xml --cov=ultron8 tests"
test-pdb="py.test --cov-config .coveragerc --verbose  --pdb --showlocals --cov-report term --cov-report xml --cov=ultron8 tests"
coverage-run="coverage run --source=ultron8/ setup.py tests; coverage report --show-missing; coverage html"
setup-test="python setup.py test"
# NOTE: This one taken from bemoonbeam_cli
run-pytest="pytest -s --tb short --cov-config .coveragerc --cov ultron8 tests --cov-report term-missing --cov-report xml:cov.xml --cov-report html:htmlcov --cov-report annotate:cov_annotate"
serve = "uvicorn ultron8.web:app --reload"
migrate = "alembic upgrade head"

[packages]
ultron8 = {path = ".", editable = true}

[dev-packages]
$(grep -v "#" requirements-dev.in | grep -v "^$" | grep -v "pytest-ipdb" | sed 's,$, = "*",g')
$(grep -v "#" requirements-doc.in | grep -v "^$" | grep -v "pytest-ipdb" | sed 's,$, = "*",g')
$(grep -v "#" requirements-test.in | grep -v "^$" | grep -v "pytest-ipdb" | sed 's,$, = "*",g')
# pytest-ipdb = {git = "git+https://github.com/mverteuil/pytest-ipdb#egg=pytest-ipdb"}

[experimental-packages]
$(grep -v "#" requirements-experimental.in | grep -v "^$" | grep -v "pytest-ipdb" | sed 's,$, = "*",g')

[pipenv]
allow_prereleases = true
EOF

\cat ${_FILE}

\cat ${_FILE} | pbcopy


echo "rm ${_TEMPDIR}"
rm -rfv ${_TEMPDIR}

popd

