#!/bin/sh
# Execute lint in a docker container to spot code mistakes.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

docker build -t ultron8-ci .
docker run --rm \
    -v `pwd`/.tox/:/usr/src/app/.tox/ \
    -t -i ultron8-ci \
    tox -e lint
