#!/usr/bin/env bash
set -e

_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Load utility bash functions
source $_DIR/message.sh

source .local.dist

export BETTER_EXCEPTIONS=1

echo -e " [run] override env vars 'SERVER_NAME' and 'SERVER_HOST' - We don't want to mess w/ ''.env.dist' for this situation \n\n"
echo -e " [run] manually set env: SERVER_NAME=localhost:11267 \n\n"
export SERVER_NAME=localhost:11267
echo -e " [run] manually set env: SERVER_HOST=http://localhost:11267 \n\n"
export SERVER_HOST=http://localhost:11267

# python script/envvar_check.py

pkill -f "ultron8/dev_serve.py" || true
pgrep -f "ultron8/dev_serve.py" || true

# if [ "x$ULTRON_CLEAN_TEST_DB" != "x" ] ; then

#     msg             "\nEnv Var ULTRON_CLEAN_DB=True. Deleting "
#     sha=`git rev-parse HEAD`;
# fi


echo -e " [run] alembic --raiseerr upgrade head\n\n"
alembic --raiseerr upgrade head

echo -e " [run] backend_pre_start.py\n\n"
python ./ultron8/api/backend_pre_start.py

echo -e " [run] initial_data.py\n\n"
python ./ultron8/initial_data.py

echo " [run] dev_serve.py\n\n"
python ultron8/dev_serve.py &
