"""create account table

Revision ID: bfe8dcff0848
Revises: 0c40da55ce5c
Create Date: 2019-08-09 20:31:10.864794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bfe8dcff0848"
down_revision = "0c40da55ce5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors_trigger_types_association",
        sa.Column("sensors_id", sa.Integer(), nullable=False),
        sa.Column("triggers_types_packs_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sensors_id"], ["sensors.id"]),
        sa.ForeignKeyConstraint(
            ["triggers_types_packs_id"], ["trigger_types.packs_id"]
        ),
        sa.PrimaryKeyConstraint("sensors_id", "triggers_types_packs_id"),
    )
    op.drop_constraint(None, "sensors", type_="foreignkey")
    op.drop_column("sensors", "trigger_types_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sensors", sa.Column("trigger_types_id", sa.INTEGER(), nullable=True))
    op.create_foreign_key(
        None, "sensors", "trigger_types", ["trigger_types_id"], ["id"]
    )
    op.drop_table("sensors_trigger_types_association")
    # ### end Alembic commands ###
