"""Feature: trigger db

Revision ID: c29296a218f9
Revises: 8a3cb9e89d31
Create Date: 2019-07-26 22:01:29.352790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c29296a218f9"
down_revision = "8a3cb9e89d31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trigger_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("occurrence_time", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trigger_events_id"), "trigger_events", ["id"], unique=False
    )
    op.create_table(
        "trigger_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column("uid", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("payload_schema", sa.JSON(), nullable=True),
        sa.Column("parameters_schema", sa.JSON(), nullable=True),
        sa.Column("packs_id", sa.Integer(), nullable=True),
        sa.Column("metadata_file", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["packs_id"], ["packs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trigger_types_id"), "trigger_types", ["id"], unique=False)
    op.create_table(
        "triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column("uid", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("ref_count", sa.Integer(), nullable=True),
        sa.Column("packs_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["packs_id"], ["packs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_triggers_id"), "triggers", ["id"], unique=False)
    op.create_table(
        "trigger_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger_type_id", sa.Integer(), nullable=True),
        sa.Column("tag", sa.String(), nullable=True),
        sa.Column("trigger_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["trigger_type_id"], ["trigger_types.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trigger_tags_id"), "trigger_tags", ["id"], unique=False)
    op.drop_index("ix_guid_tracker_expire", table_name="guid_tracker")
    op.drop_index("ix_guid_tracker_name", table_name="guid_tracker")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_guid_tracker_name", "guid_tracker", ["name"], unique=False)
    op.create_index("ix_guid_tracker_expire", "guid_tracker", ["expire"], unique=False)
    op.drop_index(op.f("ix_trigger_tags_id"), table_name="trigger_tags")
    op.drop_table("trigger_tags")
    op.drop_index(op.f("ix_triggers_id"), table_name="triggers")
    op.drop_table("triggers")
    op.drop_index(op.f("ix_trigger_types_id"), table_name="trigger_types")
    op.drop_table("trigger_types")
    op.drop_index(op.f("ix_trigger_events_id"), table_name="trigger_events")
    op.drop_table("trigger_events")
    # ### end Alembic commands ###
