"""Update: sensors

Revision ID: d7ea2612bc67
Revises: 124996a6f29e
Create Date: 2019-08-10 00:45:42.664370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7ea2612bc67"
down_revision = "124996a6f29e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("class_name", sa.String(length=255), nullable=True),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column("uid", sa.String(length=255), nullable=True),
        sa.Column("artifact_uri", sa.String(length=255), nullable=True),
        sa.Column("poll_interval", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("entry_point", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.Column("packs_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["packs_id"], ["packs.id"]),
        sa.PrimaryKeyConstraint("id", "packs_id"),
    )
    op.create_index(op.f("ix_sensors_id"), "sensors", ["id"], unique=False)
    op.create_table(
        "sensors_trigger_types_association",
        sa.Column("sensors_packs_id", sa.Integer(), nullable=False),
        sa.Column("trigger_types_packs_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sensors_packs_id"], ["sensors.packs_id"]),
        sa.ForeignKeyConstraint(["trigger_types_packs_id"], ["trigger_types.packs_id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensors_trigger_types_association")
    op.drop_index(op.f("ix_sensors_id"), table_name="sensors")
    op.drop_table("sensors")
    # ### end Alembic commands ###
